# Generated by Django 5.0.6 on 2024-05-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_name_category_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='titles',
            new_name='name',
        ),
    ]
