# Generated by Django 5.0.6 on 2024-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_titles_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
