# Generated by Django 5.0.6 on 2024-05-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_category_options_article_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
