# Generated by Django 5.0.6 on 2024-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_publish_date_article_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
