# Generated by Django 5.0.6 on 2024-05-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
    ]
