# Generated by Django 5.0.6 on 2024-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='embed_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
