# Generated by Django 5.0.6 on 2024-06-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='date',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
